[package]
name = "pathfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
log = "0.4.26"
log4rs = "1.3.0"
serde_json = "1.0.140"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
lazy_static = "1.5.0"

[dev-dependencies]
tempfile = "3.18.0"
